MyLayout:

    GridLayout:
        cols:1
        size: root.width -200, root.height -200
        pos: (100, 100)


        GridLayout:
            cols:2

            Label:
                text: 'Name'
                font_size: 30
            
            TextInput:
                multiline: False
                font_size: 35
                
        Button:
            text: 'Soumettre'
            font_size: 30
                
